import { Providers } from "@/lib/providers";
import "@/styles/globals.css";
import { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
	display: "swap",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export const viewport: Viewport = {
	colorScheme: "light dark",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={inter.className} suppressHydrationWarning>
			<body className="h-dvh">
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
